# Generated by Django 5.2.15 on 2026-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery'), ('ANY', 'Any')], default='ANY', max_length=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_first_order_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_usage_limit',
            field=models.IntegerField(blank=True, default=1, help_text='Usage limit per user', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(blank=True, help_text='Global usage limit', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, help_text='Times used globally'),
        ),
    ]
