# Generated by Django 5.2.15 on 2026-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('delivery_time_days_min', models.IntegerField(default=1)),
                ('delivery_time_days_max', models.IntegerField(default=3)),
            ],
            options={
                'unique_together': {('city', 'area', 'pin_code')},
            },
        ),
    ]
